
on: [push]

jobs:
  build:

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Boom!
    - name: Run a multi-line script
      run: ".\7L-Inentory.html"
            echo. Running...
